# Generated by Django 4.2.6 on 2023-10-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_goal',
            field=models.FloatField(null=True),
        ),
    ]
